### ISSUE TITLE
TypeError: h is not a function

### ISSUE THREAD

**Issue by josua7** [dword-design/vue-mermaid-string#65] opened 2022-01-18 16:05 UTC
Hi, I'm trying to run on Vue.js v3 and I got this error:

TypeError: h is not a function

Seems to be a change in v3 internals: "h is now globally imported instead of passed to render functions as argument"

https://github.com/vuejs/rfcs/blob/master/active-rfcs/0008-render-function-api-change.md

Thanks.

**Comment by dword-design** [comment] 2022-01-18 23:04
Hey @josua7, is the template system backward compatible? So would changing the whole thing to a Vue template fix the issue? Would be no problem for me.

**Comment by richardtz** [comment] 2022-03-31 09:56
hi, we are facing the same issue.

any chance to fix it for vue3?

thanks!

**Comment by bruceceng** [comment] 2022-08-04 18:33
I don't know exactly what your build system looks like and how you update an npm repository, but the following manual changes to index.esm.js appear to fix things for me in Vue 3 and should preserve compatibility with Vue 2 (although I didn't test that):

Add to line 2:
`import * as Vue from 'vue';`

Replace render function with:
```
  render() {
    //in Vue 2, h (createElement shortcut function) is passed as an argument to render
    let h = arguments[0];

    //in Vue 3, h is a global method.
    if (typeof h !== "function") {
      h = Vue.h;
    }

    return h("div", [this.finalValue]);
  },
```

It looks like the index.esm.js function is automatically generated by your build system though, so I don't know how you make this fix in your source code.

**Comment by blakete** [comment] 2022-12-29 22:59
Where would I find this ```index.esm.js``` file @bruceceng ?

**Comment by dword-design** [comment] 2023-02-15 15:36
Duplicate of https://github.com/dword-design/vue-mermaid-string/issues/78

**Closed by dword-design** 2023-02-15 15:36 UTC
